### ISSUE TITLE
Neovim freezes when `update_interval` is 0

### ISSUE THREAD

**Issue by bugabinga** [f-person/auto-dark-mode.nvim#20]
When `update_interval` is 0, Neovim on my system freezes (no response to input, not even C-c nor C-d) after the `quit` command.

I would like to change the code to always use a minimum threshold of 50. If below, print a warning.

OK?

**Comment by nekowinston** [comment]
I'd be against clamping it in the code itself, but maybe warn about a possible freeze in the docs.

There isn't much that's our fault here, and some users might have fast enough hardware where syncing it to framerate (16ms for 60fps) makes sense (especially when recording videos, other similar use-cases etc.).

**Comment by f-person** [comment]
Yes, I definitely agree with @nekowinston here!

**Comment by nekowinston** [comment]
Setting it to `0` also freezes my neovim. The lowest I can set it to without breaking is `5` on macOS.
The query command `defaults read -g AppleInterfaceStyle` completes in 5.6ms ± 0.3ms for me, IIRC other commands like spawning `reg.exe` in WSL can be quite a bit slower.

Instead of assuming that every system will need at least 50ms, or adding a table with minimum benchmarked values for each system, we should just get the info across that the `query_command` will have to finish within `update_interval` for a clean nvim shutdown.
